### PR TITLE
Argument Passing

### PR DESCRIPTION
**Pull request by dickensc**
Argument passing is working based on observing hex dump. :) Best we can do for now until some sys calls are implemented.

### CODE REVIEW

**Comment by dickensc** [comment]
I cannot review, it says it needs to be someone else, kinda makes sense....

**Comment by dickensc** [comment]
jk figure it out

**Comment by dickensc** [comment]
jk again "pull request authors cannot approve their own pull requests"

**Comment by bmwfire** [comment]
@dickensc In general, you should assign pull requests you do to yourself that way you'll receive an email when someone has reviewed it. Since our team is small, you can assign the rest of the team to review your PR (pull request). Every PR to the master branch will require at least one reviewer in order for it to be merged. I believe this setting will be important so that we don't merge unnecessary bugs. If nobody else does it, I'll review your PR later tonight.

**Review by bmwfire — APPROVED** [review]
Your `process_execute()` seems to meet the requirements of argument passing. Great job! I approve this PR.

**Pull request merged**
