### PR TITLE
sys calling

### PR DESCRIPTION
**Pull request by ZeroWu1412**
create the remove and create in the system calling. I also added in the user input, etc. Everything should have been label clearly.

### CODE REVIEW

**Comment by dickensc** [comment]
Why esp+4 and esp+8 in create syscall? and why are you implementing memory checking with memreaduser getuser and putuser? Brandon implemented that with is_valid_pointer? It looks like you are copying this repo: https://github.com/wookayin/pintos/blob/master/src/userprog/syscall.c pretty much exactly, we look at other people designs but copy paste coding is going to lead bugs that are really difficult to track down

**Review by dickensc — COMMENTED** [review]
Why esp+4 and esp+8 in create syscall? and why are you implementing memory checking with memreaduser getuser and putuser? Brandon implemented that with is_valid_pointer? It looks like you are copying this repo: https://github.com/wookayin/pintos/blob/master/src/userprog/syscall.c pretty much exactly, we look at other people designs but copy paste coding is going to lead bugs that are really difficult to track down.

**Comment by bmwfire** [comment]
This probably explains the multiple merge conflicts

**Review by dickensc — COMMENTED** [review]
also, filesys_lock looks undeclared before usage, and threads don't have a pcb member yet, we have to add that and looking at the diffs it doesn't look like that has been done

**Comment by ZeroWu1412** [comment]
sorry about that, i only use it as testing since it won’t run in my end. That why I did not pull until Brandon tell me too. The code will change base on the changes you guy  apply. I try to change it by tomorrow.

**Pull request closed without merging**
